### ISSUE TITLE
Why use this over tauri-plugin-sql?

### ISSUE THREAD

**Issue by joakim** [lzdyes/tauri-plugin-sqlite#6]
What are the pros/cons of using this plugin vs [tauri-plugin-sql](https://github.com/tauri-apps/tauri-plugin-sql) with the sqlite driver?

Sorry if it's obvious, but it wasn't for me :)

**Comment by volkan-a** [comment]
I wasn't able to change file paths in tauri-plugin-sql. It was the deal breaker for me.
